DROP TABLE IF EXISTS choices CASCADE;

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_code VARCHAR(255) NOT NULL,
  choice_text TEXT NOT NULL,
  borda_rank INTEGER NOT NULL DEFAULT 0
);
